name: Jorudan Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11


    - name: Install Dependencies
      run: |
        cd simple_version
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python Script
      run: |
        export PYTHONPATH=$(pwd):$PYTHONPATH
        cd simple_version
        python jorudan.py --days 1

    - name: Release create
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd simple_version
        # 日期
        date=$(date "+%Y%m%d")
        # 获取最新的JSON文件名
        latest_json=$(ls -t *.json 2>/dev/null | head -n1)
        # zip
        zip -r ${date}_json.zip ${latest_json}
        zip -r ${date}_db.zip schedule_info.sqlite
        # 创建release
        gh release create ${date}-$(git log --format=%h -1) *.zip
